

services:
  krakend:
    image: krakend:2.10.1
    ports:
      - "8085:8080"
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
      - ./lua_scripts:/etc/krakend/lua_scripts
      - ./plugin.so:/etc/krakend/plugin/plugin.so
      - /Users/velmurugan.manickavelu/.config/gcloud/application_default_credentials.json:/etc/krakend/adc.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/krakend/adc.json

    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
    depends_on:
      - api1
      - api2

  # Mock API services for testing
  api1:
    image: kennethreitz/httpbin
    ports:
      - "8001:80"

  api2:
    image: kennethreitz/httpbin
    ports:
      - "8002:80"
